### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Mearnest** [openwichita/public-meetings#31]
Where should the public meetings website go from here? We have the beginnings of a website, with some meeting content. What would make this truly useful? What are your thoughts?

**Comment by naterussmill** [comment]
- Filters on the Meeting list page are really important. I guess that would require meeting tags.
- Share buttons would be important. The use case that I'm imagining for the site is to be seeking out opportunities to get involved and then encouraging my social network to join me at an event.
- It would be awesome to get tips for attending events from people who are experienced at attending events (like Lonny) on each event page for the recurring events. Something like on one recurring meeting, "I love going to these meetings because someone can express an opinion and have it heard" or "This meeting may not be a good one for public input" etc

**Comment by Mearnest** [comment]
These are all great suggestions. We do have the beginning of a filtering system in place thanks to work done Saturday.

**Comment by kaylavix** [comment]
When I look at this, my mind is wanting it to be displayed in a calendar view. Seth mentioned in Slack that we could use google calendar.

It would be cool if we could color-code categories in that display too. Unless we run into problems of things fitting into multiple categories.

**Comment by Mearnest** [comment]
So would we use google calendar to display inside the website, or just send the data there?

**Comment by buitm1** [comment]
Filters are a great idea, but be careful not to have too many options.  I think collapsing the filter options into sectors would be more user-friendly.

**Comment by aaronarduino** [comment]
@buitm1 sectors/category like what is in this mockup? https://openwichita.slack.com/files/guruwin/F4DT74XED/openwichita-public-meetings-uiux.png

**Comment by buitm1** [comment]
@aaronarduino are you talking about the multiple filters for type category? If it works like a decision/filter tree, then yes.  I saw ["Type Category" list](http://public-meetings.website/meetings/types) and thought there were too many options here to put into one filter.

**Comment by aaronarduino** [comment]
Yeah, you got it. That is the basic idea.
